DROP TABLE IF EXISTS `souls`;
DROP TABLE IF EXISTS `soul_acl_groups`;
DROP TABLE IF EXISTS `soul_block`;
DROP TABLE IF EXISTS `soul_logs`;
DROP TABLE IF EXISTS `soul_session`;
DROP TABLE IF EXISTS `receipt_entry`;
DROP TABLE IF EXISTS `receipt_entry_details`;
DROP TABLE IF EXISTS `quick_entry`;
DROP TABLE IF EXISTS `quick_entry_details`;
DROP TABLE IF EXISTS `lookup`;
DROP TABLE IF EXISTS `lookup_value`;
DROP TABLE IF EXISTS `internal_banking`;
DROP TABLE IF EXISTS `acl_class`;
DROP TABLE IF EXISTS `acl_entry`;
DROP TABLE IF EXISTS `acl_object_identity`;
DROP TABLE IF EXISTS `dashboard_details`;
DROP TABLE IF EXISTS `dashboard`;
DROP TABLE IF EXISTS `acl_sid`;
ALTER TABLE bank_statement_import_final MODIFY COLUMN total_debit DOUBLE NOT NULL DEFAULT  '0.00';
ALTER TABLE bank_statement_import_final MODIFY COLUMN total_credit DOUBLE NOT NULL DEFAULT  '0.00';
ALTER TABLE bank_statement_import_final MODIFY COLUMN number_of_transaction int(20) NOT NULL DEFAULT '0';
ALTER TABLE company_bank_accounts MODIFY COLUMN bank_account_category varchar(50) NOT NULL DEFAULT 'cba';
