ALTER TABLE invoice_income ADD user_id int(11) NOT NULL DEFAULT  '0';
ALTER TABLE invoice_expense ADD user_id int(11) NOT NULL DEFAULT  '0';
ALTER TABLE debit_credit_gl_setup ADD private_withdrawal_code varchar(15) NOT NULL DEFAULT 1410;
DROP TRIGGER IF EXISTS after_invoice_expense_insert;
TriggerName,after_invoice_expense_insert;
DROP TRIGGER IF EXISTS after_invoice_expense_update;
TriggerName,after_invoice_expense_update;
DROP TRIGGER IF EXISTS after_invoice_expense_delete;
TriggerName,after_invoice_expense_delete;
DROP TRIGGER IF EXISTS after_invoice_income_insert;
TriggerName,after_invoice_income_insert;
DROP TRIGGER IF EXISTS after_invoice_income_update;
TriggerName,after_invoice_income_update;
DROP TRIGGER IF EXISTS after_invoice_income_delete;
TriggerName,after_invoice_income_delete;
ALTER TABLE bank_statement_import_final MODIFY COLUMN total_debit DOUBLE NOT NULL DEFAULT  '0.00';
ALTER TABLE bank_statement_import_final MODIFY COLUMN total_credit DOUBLE NOT NULL DEFAULT  '0.00';
ALTER TABLE bank_statement_import_final MODIFY COLUMN number_of_transaction int(20) NOT NULL DEFAULT '0';
ALTER TABLE company_bank_accounts MODIFY COLUMN bank_account_category varchar(50) NOT NULL DEFAULT 'cba';
